export const STEPS = {
  INTRODUCTION: "INTRODUCTION",
  REGISTRATION: "REGISTRATION",
  ABOUT: "ABOUT",
};

export const SCREENS = {
  DASHBOARD: "DASHBOARD",
  ADD_CONTACT: "ADD_CONTACT",
  CALL_OUTGOING: "CALL_OUTGOING",
  CALL_INCOMING: "CALL_INCOMING",
  CALL_INPROGRESS: "CALL_INPROGRESS",
};

export const ROUTES = {
  ANY: "*",
  ONBOARDING: "/",
  HOMEPAGE: "/homepage",
};
