export const STEPS = {
  INTRODUCTION: "INTRODUCTION",
  REGISTRATION: "REGISTRATION",
  ADD_FIRST_CONTACT: "ADD_FIRST_CONTACT",
  CALL_OUTGOING: "CALL_OUTGOING",
  CALL_INCOMING: "CALL_INCOMING",
  CALL_INPROGRESS: "CALL_INPROGRESS",
  HOMEPAGE: "HOMEPAGE",
};
