export const STEPS = {
  INTRODUCTION: "INTRODUCTION",
  REGISTRATION: "REGISTRATION",
  ABOUT: "ABOUT",
  ADD_FIRST_CONTACT: "ADD_FIRST_CONTACT",
};

export const SCREENS = {
  CALL_OUTGOING: "CALL_OUTGOING",
  CALL_INCOMING: "CALL_INCOMING",
  CALL_INPROGRESS: "CALL_INPROGRESS",
  HOMEPAGE: "HOMEPAGE",
};

export const ROUTES = {
  ANY: "*",
  ONBOARDING: "/",
  HOMEPAGE: "/homepage",
};
